### ISSUE TITLE
Moroccan phone number starting with 07 are not valid

### ISSUE THREAD

**Issue by Brahim1992** [odolbeau/phone-number-bundle#122]
Hello,

Some Moroccan phone numbers starting with 07 are not valid using this bundle like : 0711XXXXXX, 0712XXXXXX, 0713XXXXXX, 0715XXXXXX , even if the official demo of google lib phone number returns a valid result.

This is an example : https://libphonenumber.appspot.com/phonenumberparser?number=0712547208&country=MA

Is there any workaround to make this working on the bundle ?

Many thanks

**Comment by Nek-** [comment]
Hello, thank you very much for reaching out and trying to help.

This bundle is a library that makes it easy to use the [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) library. The issue you are reporting here is not related to this bundle and should be reported to the library if the issue actually exists.

But according to my test bellow, the number you gives as example (0712547208) seems to be detected as valid by libphonenumber: https://giggsey.com/libphonenumber/?phonenumber=0712547208&country=MA&language=&region=

Please try to upgrade the version of the library you're using.

I'm closing this issue since it's unrelated to the bundle and seems to be working on the library as well.
