### ISSUE TITLE
Validator cannot be instantiated  

### ISSUE THREAD

**Issue by KatzoArano** [odolbeau/phone-number-bundle#170]
Hi,
On a Sylius project (with Symfony 5.4) I get an issue during my project launch : 
`Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::__construct(): Argument #1 ($format) must be of type ?int, array given`

**Comment by KatzoArano** [comment]
https://github.com/odolbeau/phone-number-bundle/blob/67ee847f81957bdc909f681ff9f578231eed8cfa/src/Validator/Constraints/PhoneNumber.php#L56-L71

Previously, on 3.10.0 version, the constructor accepted an array as format. On my project the constructor receives an array, so if I change the `$format` type to `mixed $format` I have no errors.

**Comment by maxhelias** [comment]
Hi @KatzoArano !

Yes, since https://github.com/odolbeau/phone-number-bundle/pull/162 because it was legacy code linked to the annotation which is now better managed as an attribute.
And I see that I made a mistake during the release. 3.10.1 shouldn't exist but rather 4.0.0 to avoid this incompatibility.

**Comment by maxhelias** [comment]
3.10.1 has been remove and I created the new one : https://github.com/odolbeau/phone-number-bundle/releases/tag/v4.0.0

**Comment by maxhelias** [comment]
Zorte on 😉
