### ISSUE TITLE
Unique phone numbers

### ISSUE THREAD

**Issue by byvlad** [odolbeau/phone-number-bundle#72]
Hi!
Now I'm building system with api platform and phone-number-bundle.
But the problem is, that @Assert\Unique doesn't work with phonenumberbundle.
Do you have plan to fix it?

**Comment by odolbeau** [comment]
Hi @byvlad.

According to the [syTmfony documentation](https://symfony.com/doc/current/reference/constraints/Unique.html), this constraint does strict comparison. If you have different instance of `PhoneNumber`, everything is fine for this constraint and this is the expected behavior.

**Comment by byvlad** [comment]
@odolbeau okay, I see. but how I can check this in one row? Maybe you have plan to improve this?

**Comment by odolbeau** [comment]
Sorry for the (very) long delay.

In your case, I'll suggest to update the object you are validating in order to not add several times the same phone. If you use a `addPhone` method for example, you can use the [`equals` method provided by the library](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumber.php#L513) to check if the given phone if not already known.

Ofc, you can also create your own validator if you prefer.

Anyway, I don't think this is something to improve in the bundle: this is totally linked to your business code.
